name: "Flutter CI Action"

description: "Sets up Flutter SDK, caches the SDK and packages, and installs dependencies."

inputs:
  flutter-version:
    description: "The Flutter version to use."
    required: false
    default: "3.27.4"
  flutter-channel:
    description: "The Flutter channel to use."
    required: false
    default: "stable"
  flutter-root:
    description: "The Flutter SDK root directory."
    required: false
    default: "./flutter-sdk"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Flutter SDK
      uses: actions/cache@v3
      with:
        path: ${{ inputs.flutter-root }}
        key: ${{ runner.os }}-flutter-sdk-cache-${{ inputs.flutter-version }}-${{ inputs.flutter-channel }}
        restore-keys: |
          ${{ runner.os }}-flutter-sdk-cache-

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.flutter-channel }}

    - name: Cache Flutter packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ${{ github.workspace }}/.dart_tool
        key: ${{ runner.os }}-flutter-packages-cache-${{ hashFiles('pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-packages-cache-

    - name: Install dependencies
      run: flutter pub get
      shell: bash
