name: App Build

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build_ios:
    name: Build iOS App
    runs-on: macos-14
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-3.27.4-stable

    - name: Cache Flutter packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Setup Flutter
      uses: ./.github/actions/flutter-setup
      with:
        flutter-version: "3.27.4"
        flutter-channel: "stable"

    - name: Build iOS
      run: flutter build ios --release --no-codesign

  build_android:
    name: Build Android App
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-3.27.4-stable

    - name: Cache Flutter packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Setup Flutter
      uses: ./.github/actions/flutter-setup
      with:
        flutter-version: "3.27.4"
        flutter-channel: "stable"

    - name: Build aab
      run: flutter build appbundle --release
