name: iOS TestFlight

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  stagingDeploy:
    runs-on: macos-14
    timeout-minutes: 120

    env:
      KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APPSTORE_IDENTIFIER: ${{ secrets.APPSTORE_IDENTIFIER }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      CI: "true"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-3.27.4-stable

    - name: Cache Flutter packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
        restore-keys: ${{ runner.os }}-pub-

    - name: Setup Flutter
      uses: ./.github/actions/ci-setup
      with:
        flutter-version: "3.27.4"
        flutter-channel: "stable"

    - name: Select Xcode 15.3
      run: sudo xcode-select -s /Applications/Xcode_15.3.app

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
        working-directory: ios

    - name: Install CocoaPods
      run: gem install cocoapods
      working-directory: ios

    - name: Cache CocoaPods
      uses: actions/cache@v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}

    - name: pod install
      run: pod install --repo-update --clean-install
      working-directory: ios

    - name: Flutter build (no codesign)
      run: flutter build ios --release --no-codesign

    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-dd-${{ hashFiles('ios/Podfile.lock') }}-${{ hashFiles('pubspec.lock') }}
        restore-keys: ${{ runner.os }}-dd-

    - name: Write ASC API key
      run: |
        echo "${{ secrets.APPSTORE_KEY_JSON }}" | base64 -d > ios/key.json

    - name: fastlane beta
      run: |
        set -eo pipefail
        cd ios
        bundle exec fastlane ios beta --verbose 2>&1 | tee fastlane.log
      env:
        APP_STORE_CONNECT_API_KEY_PATH: ./key.json
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.ASC_PASSWORD }}
        FASTLANE_XCODEBUILD_LOGS: "1" 

    - name: Error logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: fastlane-build-logs
        path: |
          ios/fastlane.log
          ios/fastlane/build_logs/**/*.log
          $HOME/Library/Logs/gym