name: Flutter Analyze Code

on:
  pull_request:
    branches:
      - develop

env:
  flutter_version: 3.27.4

jobs:
  test:
    name: Analyze Code
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/ci-setup
        with:
          flutter-root: ${{ github.workspace }}/flutter-sdk

      - name: Analyze Code
        run: flutter analyze
