name: Flutter Unit Tests

on:
  pull_request:
    branches:
      - develop

env:
  flutter_version: 3.27.4

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/ci-setup
        with:
          flutter-root: ${{ github.workspace }}/flutter-sdk

      - name: Run tests
        run: flutter test
