name: iOS TestFlight

on:
  push:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  stagingDeploy:
    runs-on: macos-14
    timeout-minutes: 60

    env:
      KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      CI: "true"

    steps:
    
    #--------------------------------------------------
    # Checkout
    #--------------------------------------------------
    - uses: actions/checkout@v4

    #--------------------------------------------------
    # Flutter SDK
    #--------------------------------------------------
    - name: Setup Flutter
      uses: ./.github/actions/ci-setup
      with:
        flutter-root: ${{ github.workspace }}/flutter-sdk

    #--------------------------------------------------
    # Xcode 15.43
    #--------------------------------------------------
    - name: Select Xcode 15.3
      run: sudo xcode-select -s /Applications/Xcode_15.3.app

    #--------------------------------------------------
    # Ruby 3.3 + CocoaPods
    #--------------------------------------------------
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
        working-directory: ios

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod repo update
      working-directory: ios

    # CocoaPods の bin を次ステップ以降にも見せる
    - run: echo "$HOME/.gem/ruby/3.3.0/bin" >> $GITHUB_PATH

    #--------------------------------------------------
    # Resolve Pods
    #--------------------------------------------------
    - name: pod install
      run: |
        cd ios
        pod install --repo-update

    #--------------------------------------------------
    # App Store Connect API キーを安全に保存
    #    （json または p8 を **base64** したものを Secret に）
    #--------------------------------------------------
    - name: Write ASC API key
      run: |
        echo "${{ secrets.APPSTORE_KEY_JSON }}" | base64 -d > ios/key.json

    #--------------------------------------------------
    # Fastlane
    #--------------------------------------------------
    - name: fastlane beta
      run: |
        cd ios
        bundle exec fastlane beta
      env:
        APP_STORE_CONNECT_API_KEY_PATH: ./key.json
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.ASC_PASSWORD }}
